#!/usr/py/python37/bin/python3

# Google reference for SMTP setup: https://support.google.com/mail/answer/7126229?visit_id=636933472854975930-1892577040&hl=pt-BR&rd=1

import os, sys, json, argparse
from dotenv import load_dotenv
from smtplib import SMTP_SSL
from email.message import EmailMessage

def list_or_json(filename):
	addr_list = []
	with open(filename, "r") as addr_file:
		file_content = addr_file.read()
		try:
			addr_list = json.loads(file_content)
		except json.JSONDecodeError:
			addr_list = file_content.split('\n')
	return addr_list

# Parsing arguments
parser = argparse.ArgumentParser(description="Send emails via cli.")
parser.add_argument('-b', "--body", type=argparse.FileType('r'), default=sys.stdin, metavar="body_message",
	help="Name of file containing body message. It can also be passed through pipes to stdin.")
parser.add_argument('-t', "--title", type=str, default="Python script email :)", metavar="email_title",
	help="Title of the email.")
parser.add_argument('-ml', "--mailing-list", type=list_or_json, dest="addr_list", metavar="addresses_filename",
	help="Name of file containing mailing list. Can be a JSON list file.", required=True)

args = parser.parse_args(sys.argv[1:])

# Setting up environment variables
load_dotenv('./email.env')

from_addr = os.getenv("EMAIL")
password = os.getenv("PASSWORD")
host = os.getenv("SMTP_HOST")
port = os.getenv("SMTP_PORT")

# Setting email
msg = EmailMessage()
msg.set_content(args.body.read())
msg['Subject'] = args.title
msg['From'] = from_addr

# Sending emails
with SMTP_SSL(host=host, port=port) as smtp:
	smtp.login(from_addr, password)

	print("Sending email to: %s" % (args.addr_list))
	msg['To'] = args.addr_list
	smtp.send_message(msg)